
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: basic-pipeline-run-
spec:
  pipelineRef:
    name: basic-pipeline
  params:
    - name: "git-url"
      value: "https://github.com/pittar-sandbox/dotnet-contoso-app.git"
    - name: "git-revision"
      value: "main"
    - name: "app-name"
      value: "dotnet-example"
    - name: "namespace"
      value: "dotnet-basic-pipeline"
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: build-workspace
