
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: quarkus-native-basic-pipeline-
spec:
  pipelineRef:
    name: quarkus-native-basic-pipeline
  params:
    - name: "git-url"
      value: "https://github.com/pittar-sandbox/quarkus-rest.git"
    - name: "git-revision"
      value: "main"
    - name: "app-name"
      value: "quarkus-native-example"
    - name: "namespace"
      value: "quarkus-native-basic-pipeline"
  workspaces:
    - name: build-workspace
      persistentVolumeClaim:
        claimName: build-workspace
    - name: maven-settings
      emptyDir: {}
      
