apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: download-model
spec:
  params:
    - description: Hugginface token.
      name: HF_TOKEN
      type: string
    - description: Model to download.
      name: MODEL
      type: string
  tasks:
    - name: download-model
      params:
        - name: HF_TOKEN
          value: $(params.HF_TOKEN)
        - name: MODEL
          value: $(params.MODEL)
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: download-model-hf
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: model
          workspace: model
  workspaces:
    - name: model
