apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: quarkus-native-build
spec:
  description: This Task can be used to run a Quaruks native build.
  params:
    - name: BUILDER_IMAGE
      type: string
      description: Quarkus/Maven/GraalVM base image.
      default: quay.io/quarkus/ubi-quarkus-native-s2i:20.3-java11
    - name: GOALS
      type: array
      description: Maven goals to run.
      default:
        - package
        - -Pnative
    - name: MAVEN_MIRROR_URL
      type: string
      description: The Maven repository mirror url.
      default: ''
    - name: PROXY_USER
      type: string
      description: The username for the proxy server.
      default: ''
    - name: PROXY_PASSWORD
      type: string
      description: The password for the proxy server.
      default: ''
    - name: PROXY_PORT
      type: string
      description: Port number for the proxy server.
      default: ''
    - name: PROXY_HOST
      type: string
      description: Proxy server Host.
      default: ''
    - name: PROXY_NON_PROXY_HOSTS
      type: string
      description: Non proxy server host.
      default: ''
    - name: PROXY_PROTOCOL
      type: string
      description: Protocol for the proxy ie http or https.
      default: http
  steps:
    - image: 'registry.access.redhat.com/ubi8/ubi-minimal:8.3'
      name: mvn-settings
      resources: {}
      script: >
        #!/usr/bin/env bash


        [[ -f $(workspaces.maven-settings.path)/settings.xml ]] && \

        echo 'using existing $(workspaces.maven-settings.path)/settings.xml' &&
        exit 0


        cat > $(workspaces.maven-settings.path)/settings.xml <<EOF

        <settings>
          <mirrors>
            <!-- The mirrors added here are generated from environment variables. Don't change. -->
            <!-- ### mirrors from ENV ### -->
          </mirrors>
          <proxies>
            <!-- The proxies added here are generated from environment variables. Don't change. -->
            <!-- ### HTTP proxy from ENV ### -->
          </proxies>
        </settings>

        EOF


        xml=""

        if [ -n "$(params.PROXY_HOST)" -a -n "$(params.PROXY_PORT)" ]; then
          xml="<proxy>\
            <id>genproxy</id>\
            <active>true</active>\
            <protocol>$(params.PROXY_PROTOCOL)</protocol>\
            <host>$(params.PROXY_HOST)</host>\
            <port>$(params.PROXY_PORT)</port>"
          if [ -n "$(params.PROXY_USER)" -a -n "$(params.PROXY_PASSWORD)" ]; then
            xml="$xml\
                <username>$(params.PROXY_USER)</username>\
                <password>$(params.PROXY_PASSWORD)</password>"
          fi
          if [ -n "$(params.PROXY_NON_PROXY_HOSTS)" ]; then
            xml="$xml\
                <nonProxyHosts>$(params.PROXY_NON_PROXY_HOSTS)</nonProxyHosts>"
          fi
          xml="$xml\
              </proxy>"
          sed -i "s|<!-- ### HTTP proxy from ENV ### -->|$xml|" $(workspaces.maven-settings.path)/settings.xml
        fi


        if [ -n "$(params.MAVEN_MIRROR_URL)" ]; then
          xml="    <mirror>\
            <id>mirror.default</id>\
            <url>$(params.MAVEN_MIRROR_URL)</url>\
            <mirrorOf>central</mirrorOf>\
          </mirror>"
          sed -i "s|<!-- ### mirrors from ENV ### -->|$xml|" $(workspaces.maven-settings.path)/settings.xml
        fi
    - args:
        - '-s'
        - $(workspaces.maven-settings.path)/settings.xml
        - $(params.GOALS)
      command:
        - /usr/bin/mvn
      image: $(params.BUILDER_IMAGE)
      name: mvn-goals
      resources: {}
      workingDir: $(workspaces.source.path)
  workspaces:
    - description: The workspace consisting of maven project.
      name: source
    - description: >-
        The workspace consisting of the custom maven settings provided by the
        user.
      name: maven-settings