apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dotnet-basic-pipeline

# Include the dotnet cli Task from Re Hat Canada Catalog.
bases:
  - github.com/redhat-canada-gitops/catalog/openshift-pipelines-tasks/maven/base

# Workspace PVC, Pipeline, and Pipeline Run
resources:
  - namespace.yaml
  - workspace-pvc.yaml
  - basic-pipeline.yaml
